---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web.photostream.topic.pv
  labels:
    app: photostream
  namespace: web
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/persistentvolumes/web/photostream/topic
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web.photostream.topic.pvc
  labels:
    app: photostream
  namespace: web
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: web.photostream.topic.pv
